# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4520f201856fc55d2bf511b374303f162190e1630bb2b0e03521a75110fb162fab24933600b4839f16ee610118e9677f90e97aadab156a5be406d7117665ac3c

test:
  secret_key_base: f29dfbc5b00190b5a520778e893367ab6a9ab1a12e5379086fd5c3918aa159a787e8b6ebc04c4994d57aec413dbfc7fd59559944e28fe61180745bfccc82826c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
